# =============================================================================
# Docker Compose Queue-Only Override
# =============================================================================
# Use this file for queue-only deployments with minimal services.
# Usage: docker-compose -f docker-compose.base.yml -f docker-compose.queue.override.yml up

version: '3.8'

services:
  # =============================================================================
  # Queue Services Only
  # =============================================================================
  queued:
    image: ghcr.io/oculairmedia/graphiti-queued:latest
    container_name: graphiti-queued-simple
    restart: unless-stopped
    ports:
      - "${QUEUE_PORT:-8080}:8080"
    volumes:
      - queued_data:/data
    environment:
      - QUEUED_DATA_DIR=/data
      - QUEUED_BIND_ADDR=0.0.0.0:8080
      - RUST_LOG=${RUST_LOG:-info}
    networks:
      - graphiti_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/queues"]
      interval: 10s
      timeout: 5s
      retries: 3
    labels:
      - homepage.group=Knowledge Management
      - homepage.name=Simple Queue
      - homepage.icon=si-rabbitmq
      - homepage.href=http://192.168.50.90:${QUEUE_PORT:-8080}
      - homepage.description=Lightweight message queue

  # =============================================================================
  # Single Worker for Processing
  # =============================================================================
  graphiti-worker:
    image: ghcr.io/oculairmedia/graphiti-worker:latest
    container_name: graphiti-worker-simple
    restart: unless-stopped
    environment:
      - QUEUED_URL=http://queued:8080
      - FALKORDB_HOST=${FALKORDB_HOST:-falkordb}
      - FALKORDB_PORT=${FALKORDB_PORT:-6379}
      - FALKORDB_DATABASE=${FALKORDB_DATABASE:-graphiti_migration}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-dummy}
      - USE_OLLAMA=${USE_OLLAMA:-true}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://100.81.139.20:11434/v1}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-gemma3:12b}
      - OLLAMA_EMBEDDING_MODEL=${OLLAMA_EMBEDDING_MODEL:-mxbai-embed-large:latest}
      - WORKER_COUNT=${WORKER_COUNT:-2}
      - BATCH_SIZE=${BATCH_SIZE:-5}
      - POLL_INTERVAL=${POLL_INTERVAL:-2.0}
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - graphiti_network
    depends_on:
      queued:
        condition: service_healthy
      falkordb:
        condition: service_healthy
    labels:
      - homepage.group=Knowledge Management
      - homepage.name=Simple Worker
      - homepage.icon=si-kubernetes
      - homepage.description=Lightweight queue worker

  # Remove unused services from base
  graphiti-centrality-rs:
    profiles:
      - disabled

  graphiti-search-rs:
    profiles:
      - disabled

  graph-visualizer-rust:
    profiles:
      - disabled

  redis:
    profiles:
      - disabled

volumes:
  queued_data:
    driver: local
    labels:
      - description=Simple queue data storage