services:
  falkordb:
    image: falkordb/falkordb:latest
    ports:
      - "6379:6379" # FalkorDB
      - "3000:3000" # FalkorDB Browser
    volumes:
      - falkordb_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  graphiti-mcp:
    image: ghcr.io/oculairmedia/graphiti-mcp:feature-mcp-fastmcp-enhancement
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false # Makes the file optional. Default value is 'true'
    depends_on:
      falkordb:
        condition: service_healthy
    environment:
      - FALKORDB_URI=${FALKORDB_URI:-falkordb://falkordb:6379}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - PATH=/root/.local/bin:${PATH}
      - SEMAPHORE_LIMIT=${SEMAPHORE_LIMIT:-10}
    ports:
      - "8000:8000" # Expose the MCP server via HTTP for SSE transport
    command: ["uv", "run", "graphiti_mcp_server.py", "--transport", "sse"]

volumes:
  falkordb_data:
