#!/usr/bin/env python3
from pathlib import Path

OLD = """    async def run(self, query: str | list, **kwargs: Any) -> Any:\n        # FalkorDB does not support argument for Label Set, so it's converted into an array of queries\n        if isinstance(query, list):\n            for cypher, params in query:\n                params = convert_datetimes_to_strings(params)\n                cypher = _wrap_vector_params_in_query(str(cypher), params)\n                await self.graph.query(cypher, params)  # type: ignore[reportUnknownArgumentType]\n        else:\n            params = _flatten_params(dict(kwargs))\n            params = convert_datetimes_to_strings(params)\n            query = _wrap_vector_params_in_query(str(query), params)\n            await self.graph.query(query, params)  # type: ignore[reportUnknownArgumentType]\n        # Assuming `graph.query` is async (ideal); otherwise, wrap in executor\n        return None\n\n"""

NEW = """    async def run(self, query: str | list, **kwargs: Any) -> Any:\n        # FalkorDB does not support argument for Label Set, so it's converted into an array of queries\n        if isinstance(query, list):\n            for cypher, params in query:\n                params = convert_datetimes_to_strings(params)\n                wrapped_cypher = _wrap_vector_params_in_query(str(cypher), params)\n                if logger.isEnabledFor(logging.DEBUG):\n                    logger.debug(\"Falkor RUN(list) query:\\n%s\\nparams=%s\", wrapped_cypher, params)\n                try:\n                    await self.graph.query(wrapped_cypher, params)  # type: ignore[reportUnknownArgumentType]\n                except Exception:\n                    logger.error(\n                        \"Falkor RUN(list) query failed:\\n%s\\nparams=%s\",\n                        wrapped_cypher,\n                        params,\n                        exc_info=True,\n                    )\n                    raise\n        else:\n            params = _flatten_params(dict(kwargs))\n            params = convert_datetimes_to_strings(params)\n            wrapped_query = _wrap_vector_params_in_query(str(query), params)\n            if logger.isEnabledFor(logging.DEBUG):\n                logger.debug(\"Falkor RUN query:\\n%s\\nparams=%s\", wrapped_query, params)\n            try:\n                await self.graph.query(wrapped_query, params)  # type: ignore[reportUnknownArgumentType]\n            except Exception:\n                logger.error(\n                    \"Falkor RUN query failed:\\n%s\\nparams=%s\",\n                    wrapped_query,\n                    params,\n                    exc_info=True,\n                )\n                raise\n        # Assuming `graph.query` is async (ideal); otherwise, wrap in executor\n        return None\n\n"""

path = Path('/opt/stacks/graphiti/graphiti_core/driver/falkordb_driver.py')
text = path.read_text()
if OLD not in text:
    raise SystemExit('pattern not found')
path.write_text(text.replace(OLD, NEW))
print('updated run method with debug logging')
