[workspace]
resolver = "2"
members = [
  "benchmarker",
  "libqueued",
  "queued",
  "queued-client-rs",
  "stochastic-stresser",
]

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
