name: Build and Push Worker Service Container

on:
  push:
    branches: [ main, ingestion-queue-system, falkordb-corruption-fixes, data-validation-framework, feature/chutes-ai-integration ]
    paths:
      - 'worker/**'
      - 'graphiti_core/**'
      - '.github/workflows/build-worker-service.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'worker/**'
      - 'graphiti_core/**'
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-worker

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 1
        submodules: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./worker/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        no-cache: ${{ github.event_name == 'workflow_dispatch' }}
        cache-from: |
          type=gha
        cache-to: |
          type=gha,mode=max
        platforms: linux/amd64
        build-args: |
          BUILDKIT_PROGRESS=plain
          CACHE_BUST=${{ github.sha }}

    - name: Output image details
      if: success()
      run: |
        echo "✅ Worker service image successfully built and pushed!"
        echo "📦 Registry: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
        echo "🏷️  Tags: ${{ steps.meta.outputs.tags }}"