name: Type Safety Check (Pyright + Mypy)

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  type-check:
    runs-on: depot-ubuntu-22.04
    environment: development
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Run Pyright for graphiti-core
        shell: bash
        run: |
          uv run pyright ./graphiti_core
      - name: Install graph-service dependencies
        shell: bash
        run: |
          cd server
          uv sync --all-extras
          # Install type checking tools
          uv pip install mypy pyright
      - name: Run Pyright for graph-service
        shell: bash
        run: |
          cd server
          # Pyright will use the stubPath configured in pyproject.toml
          uv run pyright .
      - name: Run Mypy for graph-service
        shell: bash
        run: |
          cd server
          # Mypy will use the configuration in pyproject.toml
          MYPYPATH=typings uv run mypy graph_service --config-file pyproject.toml || true
          # Note: Using || true temporarily to not fail builds while fixing existing type issues
          # Remove || true once all type errors are resolved
