# Sync Service Configuration
# This file provides default configuration values that can be overridden by environment variables

neo4j:
  uri: "bolt://neo4j:7687"
  user: "neo4j"
  password: "demodemo" 
  database: "neo4j"
  pool_size: 10

falkordb:
  host: "falkordb"
  port: 6379
  username: null
  password: null
  database: "graphiti_migration"

sync:
  interval_seconds: 180  # 3 minutes (more frequent backup)
  batch_size: 500        # Smaller batches for reliability
  full_sync_on_startup: false  # Disable automatic startup sync (we'll handle intelligently)
  enable_incremental: false    # Forward sync disabled
  enable_continuous: true      # Enable continuous sync
  sync_direction: "reverse"    # FalkorDB → Neo4j (reverse sync)
  enable_reverse_incremental: true  # Enable reverse incremental sync
  max_retries: 5          # More retries for reliability
  retry_delay_seconds: 15 # Faster retry recovery
  auto_recovery: true     # Enable automatic disaster recovery

logging:
  level: "INFO"
  format: "json"
  file_path: null  # Log to stdout if null
  max_file_size_mb: 100
  backup_count: 5

monitoring:
  health_port: 8080
  health_path: "/health"
  metrics_enabled: true
  metrics_port: 8081
  metrics_path: "/metrics"